class MotionInitializers
  
end

# List of Classes that should be reviewed. Maybe.

# NSObject
# NSFileProviderExtension
# NSLayoutConstraint
# NSLayoutManager
# NSMutableParagraphStyle
# NSShadow
# NSStringDrawingContext
# NSTextAttachment
# NSTextContainer
# NSTextTab
# UIAcceleration
# UIAccelerometer
# UIAccessibilityCustomAction
# UIAccessibilityElement
# UIActivity
# UIAlertAction
# UIBarItem
# UIBarButtonItem
# UITabBarItem
# UIBezierPath
# UICollectionViewLayout
# UICollectionViewFlowLayout
# UICollectionViewTransitionLayout
# UICollectionViewLayoutAttributes
# UICollectionViewLayoutInvalidationContext
# UICollectionViewFlowLayoutInvalidationContext
# UICollectionViewUpdateItem
# UIColor
# UIDevice
# UIDictationPhrase
# UIDocument
# UIManagedDocument
# UIDocumentInteractionController
# UIDynamicAnimator
# UIDynamicBehavior
# UIAttachmentBehavior
# UICollisionBehavior
# UIDynamicItemBehavior
# UIGravityBehavior
# UIPushBehavior
# UISnapBehavior
# UIEvent
# UIFont
# UIFontDescriptor
# UIGestureRecognizer
# UILongPressGestureRecognizer
# UIPanGestureRecognizer
# UIScreenEdgePanGestureRecognizer
# UIPinchGestureRecognizer
# UIRotationGestureRecognizer
# UISwipeGestureRecognizer
# UITapGestureRecognizer
# UIImage
# UIImageAsset
# UIKeyCommand
# UILexicon
# UILexiconEntry
# UILocalizedIndexedCollation
# UILocalNotification
# UIMenuController
# UIMenuItem
# UIMotionEffect
# UIInterpolatingMotionEffect
# UIMotionEffectGroup
# UINavigationItem
# UINib
# UIPasteboard
# UIPercentDrivenInteractiveTransition
# UIPopoverController
# UIPresentationController
# UIPopoverPresentationController
# UIPrinter
# UIPrinterPickerController
# UIPrintFormatter
# UIMarkupTextPrintFormatter
# UISimpleTextPrintFormatter
# UIViewPrintFormatter
# UIPrintInfo
# UIPrintInteractionController
# UIPrintPageRenderer
# UIPrintPaper
# UIResponder
# UIApplication
# UIView
# UIActionSheet
# UIActivityIndicatorView
# UIAlertView
# UICollectionReusableView
# UICollectionViewCell
# UIControl
# UIButton
# UIDatePicker
# UIPageControl
# UIRefreshControl
# UISegmentedControl
# UISlider
# UIStepper
# UISwitch
# UITextField
# UIImageView
# UIInputView
# UILabel
# UINavigationBar
# UIPickerView
# UIPopoverBackgroundView
# UIProgressView
# UIScrollView
# UICollectionView
# UITableView
# UITextView
# UISearchBar
# UITabBar
# UITableViewCell
# UITableViewHeaderFooterView
# UIToolbar
# UIVisualEffectView
# UIWebView
# UIWindow
# UIViewController
# UIActivityViewController
# UIAlertController
# UICollectionViewController
# UIDocumentMenuViewController
# UIDocumentPickerExtensionViewController
# UIDocumentPickerViewController
# UIInputViewController
# UINavigationController
# UIImagePickerController
# UIVideoEditorController
# UIPageViewController
# UIReferenceLibraryViewController
# UISearchController
# UISplitViewController
# UITabBarController
# UITableViewController
# UIScreen
# UIScreenMode
# UISearchDisplayController
# UIStoryboard
# UIStoryboardSegue
# UIStoryboardPopoverSegue
# UITableViewRowAction
# UITextChecker
# UITextInputMode
# UITextInputStringTokenizer
# UITextPosition
# UITextRange
# UITextSelectionRect
# UITouch
# UITraitCollection
# UIUserNotificationAction
# UIMutableUserNotificationAction
# UIUserNotificationCategory
# UIMutableUserNotificationCategory
# UIUserNotificationSettings
# UIVisualEffect
# UIBlurEffect
# UIVibrancyEffect
# NSMutableAttributedString
# NSTextStorage
# NSOperation
